### ISSUE TITLE
Multiple operations only writes changes when last op has changes

### ISSUE THREAD

**Issue by SasBer** [particledecay/ansible-jsonpatch#15]
When multiple op are done and the last op does not change the file, the previous changes are not written.

Steps to reproduce
1) Run a task against a file with multiple operations where the last operation does not change the value of the path.
- json_patch:
    src: /tims/etc/PaiConfiguration.json
    operations:
      - op: replace
        path: /fgaActive
        value: "{{ PAI_fgaActive }}"
      - op: replace
        path: /fgaContactType
        value: "{{ PAI_fgaContactType }}"
      - op: replace
        path: /uwcDoorSignalActive
        value: "{{ PAI_uwcDoorSignalActive }}"
      - op: replace
        path: /uwcDoorSignalContactType
        value: "{{ PAI_uwcDoorSignalContactType }}"
    pretty: yes
2) The ansible debug output shows the changes that should me done, but the when checking the file, it is still the same.

This also happens when no Ansible variables, but strings are used.

Workaround:
Add two dummy operations at the end which guarantees a change:
      - op: add
        path: /dummy
        value: "{{ ansible_date_time.iso8601_basic_short }}"
      - op: remove
        path: /dummy

**Comment by tboerger** [comment]
I can confirm that this is really an issue that is still present :(

**Comment by particledecay** [comment]
My bad, I must have accidentally deleted this notification. Only noticed with the latest comment. Hopefully I'll have a fix in soon.

**Comment by particledecay** [comment]
I made a quick change and re-ran the ansible integration tests (I added a simple multi-op test to verify), and it works. See if this works for you.
