### ISSUE TITLE
License mismatch in project files

### ISSUE THREAD

**Issue by barorion** [ParticleDecay/ansible-jsonpatch#3]
[LICENSE FILE](https://github.com/ParticleDecay/ansible-jsonpatch/blob/master/LICENSE) states MIT license while header of [jsonpatch.py](https://github.com/ParticleDecay/ansible-jsonpatch/blob/master/jsonpatch.py) states GPL-3.0.

**Comment by ParticleDecay** [comment]
Oh, good catch. Thank you!
