### ISSUE TITLE
[Feature Request] Support for file creation

### ISSUE THREAD

**Issue by meersjo** [particledecay/ansible-jsonpatch#6]
Many other modules support a create: parameter, that indicates wether a nonexistent target file should be created at runtime.

This saves a touch operation earlier in the playbook, so I would ask for this to be added.

**Comment by particledecay** [comment]
I like this idea. Would you be interested in submitting a PR? Otherwise, I can take a look at it maybe this weekend.

**Comment by meersjo** [comment]
I'm afraid it's a little beyond me, having zero experience with python 😅

Sent from Nine
________________________________

**Comment by particledecay** [comment]
@meersjo I've been crazy busy, but this functionality should now be in the latest master. The README has been updated to include the new options.

**Comment by meersjo** [comment]
Perfect, thank you :-)
