### ISSUE TITLE
wish: support --diff

### ISSUE THREAD

**Issue by tpo** [particledecay/ansible-jsonpatch#9]
json_patch works as advertized:

<pre>
$ ansible-playbook rojava.yml --check --diff

PLAY [rojava] **********************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************************************************************************************
ok: [rojava]

TASK [service : enable alerts] ****************************************************************************************************************************************************************************************
changed: [rojava]

PLAY RECAP *************************************************************************************************************************************************************************************************************************
rojava                     : ok=2    changed=1    unreachable=0    failed=0   
</pre>

However it'd be very nice, if it could display the `diff` of what it would have done.

Thanks,
*t

**Comment by mastervolkov** [comment]
@tpo Can you test my change in pull request https://github.com/particledecay/ansible-jsonpatch/pull/13 . Simple, but work for me

**Comment by mastervolkov** [comment]
@tpo Changes in master. You can test and close issue

**Comment by tpo** [comment]
@mastervolkov 's patch has landed in master. Thanks a lot @mastervolkov & @particledecay -> closing
